---
- name: Install MySQL packages
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    state: present

- name: Create `.my.cnf` for root
  template:
    src: root_my_cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Remove anonymous MySQL users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Application Database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Application DB User
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    host: localhost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
